import type { Metadata } from "next";
import Link from "next/link";
import { Page } from "../SiteChrome";
import { localizedHref, resolveLanguage } from "../i18n";
export const metadata: Metadata = { title: "Chi sono — Alexandra Huaman", description: "Formazione, esperienza e visione di Alexandra Huaman." };
const content={
 it:{kicker:"01 · Chi sono",title:<>Arte, tecnica<br/><em>e ascolto.</em></>,intro:"Una formazione multidisciplinare, una pratica viva e un modo profondamente umano di accompagnare ogni persona nel movimento.",first:"Laureata in Arti Sceniche con specializzazione in Danza presso la Pontificia Universidad Católica del Perú (PUCP).",second:"Dal 2015 mi occupo di insegnamento della danza e del movimento con bambini, adulti e performer. La mia formazione integra danza contemporanea, danza classica, ricerca del movimento e arti circensi.",quote:"“È il modo più autentico che abbiamo per prenderci cura di noi stessi.”",cta:"Esplora le competenze",since:"Dal 2015",values:[["Presenza","Ogni lezione parte dall’ascolto: del corpo, del respiro e del momento presente."],["Curiosità","La ricerca apre possibilità nuove, senza giudizio e senza modelli rigidi."],["Cura","Un ambiente sicuro, inclusivo e motivante dove ciascuno può ritrovare il piacere di muoversi."]]},
 en:{kicker:"01 · About",title:<>Art, technique<br/><em>and listening.</em></>,intro:"A multidisciplinary education, a living practice and a deeply human way of guiding each person through movement.",first:"I hold a degree in Performing Arts with a specialization in Dance from the Pontifical Catholic University of Peru (PUCP).",second:"Since 2015, I have taught dance and movement to children, adults and performers. My training brings together contemporary dance, classical dance, movement research and circus arts.",quote:"“It is the most authentic way we have to care for ourselves.”",cta:"Explore my expertise",since:"Since 2015",values:[["Presence","Every session begins with listening: to the body, the breath and the present moment."],["Curiosity","Exploration opens new possibilities, without judgement or rigid models."],["Care","A safe, inclusive and encouraging environment where everyone can rediscover the pleasure of moving."]]}
};
export default async function About({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){const language=await resolveLanguage(searchParams);const c=content[language];return <Page language={language} kicker={c.kicker} title={c.title} intro={c.intro}><section className="about-grid"><div className="image-panel image-stretch"><span>{c.since}</span></div><div className="story"><p className="dropcap">{c.first}</p><p>{c.second}</p><blockquote>{c.quote}</blockquote><Link className="inline-arrow" href={localizedHref("/competenze",language)}>{c.cta} <span>→</span></Link></div></section><section className="values">{c.values.map((value,i)=><article key={value[0]}><small>0{i+1}</small><h2>{value[0]}</h2><p>{value[1]}</p></article>)}</section></Page>}
