import type { Metadata } from "next";
import { Page } from "../SiteChrome";
import { resolveLanguage } from "../i18n";
export const metadata: Metadata = { title: "Competenze — Alexandra Huaman", description: "Danza, movimento e corpo, arti circensi." };
const content={
 it:{kicker:"03 · Formazione e competenze",title:<>Il sapere diventa<br/><em>esperienza.</em></>,intro:"Danza, anatomia, educazione somatica e discipline circensi dialogano in un metodo completo, adattabile e professionale.",approach:"Il mio approccio",methodTitle:<>Ogni corpo è unico.<br/>Ogni movimento ha un significato.</>,method:"Le mie lezioni uniscono tecnica, sensibilità e ascolto per creare un ambiente sicuro, inclusivo e motivante. La disciplina non limita: offre gli strumenti per muoversi con più libertà.",skills:[{mark:"D",title:"Danza",items:["Danza contemporanea","Danza classica","Composizione e ricerca del movimento","Improvvisazione","Espressione corporea"]},{mark:"M",title:"Movimento e corpo",items:["Anatomia applicata al movimento","Educazione somatica","Analisi del movimento","Mobilità e flessibilità","Preparazione fisica"]},{mark:"A",title:"Arti circensi",items:["Tessuti aerei","Discipline circensi","Allenamento acrobatico","Controllo corporeo e forza funzionale"]}]},
 en:{kicker:"03 · Education & expertise",title:<>Knowledge becomes<br/><em>experience.</em></>,intro:"Dance, anatomy, somatic education and circus disciplines come together in a complete, adaptable and professional method.",approach:"My approach",methodTitle:<>Every body is unique.<br/>Every movement has meaning.</>,method:"My sessions bring together technique, sensitivity and listening to create a safe, inclusive and motivating environment. Discipline does not restrict: it offers the tools to move with greater freedom.",skills:[{mark:"D",title:"Dance",items:["Contemporary dance","Classical dance","Movement composition and research","Improvisation","Physical expression"]},{mark:"M",title:"Movement & body",items:["Applied movement anatomy","Somatic education","Movement analysis","Mobility and flexibility","Physical conditioning"]},{mark:"C",title:"Circus arts",items:["Aerial silks","Circus disciplines","Acrobatic training","Body control and functional strength"]}]}
};
export default async function Skills({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){const language=await resolveLanguage(searchParams);const c=content[language];return <Page language={language} kicker={c.kicker} title={c.title} intro={c.intro}><section className="skill-grid">{c.skills.map((s,i)=><article key={s.title}><div className="skill-mark">{s.mark}</div><small>0{i+1}</small><h2>{s.title}</h2><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</section><section className="method-banner"><div className="image-panel image-barre"></div><div><p className="eyebrow">{c.approach}</p><h2>{c.methodTitle}</h2><p>{c.method}</p></div></section></Page>}
