import type { Metadata } from "next";
import { Page } from "../SiteChrome";
import { resolveLanguage } from "../i18n";
export const metadata: Metadata = { title: "Competenze — Alexandra Huaman", description: "Danza, movimento, arti circensi, pedagogia e ricerca." };
const sourceContent={
 it:{kicker:"03 · Formazione e competenze",title:<>Il sapere diventa<br/><em>esperienza.</em></>,intro:"Danza, tradizioni peruviane, teatro, circo e pedagogia dialogano in una pratica interdisciplinare, adattabile e professionale.",approach:"Il mio approccio",methodTitle:<>Ogni corpo è unico.<br/>Ogni movimento ha un significato.</>,method:"Le lezioni uniscono tecnica, sensibilità e ascolto con strumenti nati dalla scena, dalla pedagogia e dalla ricerca. L’obiettivo è creare uno spazio sicuro e motivante dove la disciplina diventa autonomia e libertà espressiva.",skills:[{mark:"D",title:"Danza",items:["Danza contemporanea e classica","Danze tradizionali peruviane","Composizione e coreografie di gruppo","Improvvisazione","Danza aerea"]},{mark:"C",title:"Circo e scena",items:["Tessuti e acrobatica aerea","Circo contemporaneo e sociale","Teatro corporeo e clown","Personaggi, animazione e trampoli","Creazione scenica interdisciplinare"]},{mark:"M",title:"Movimento e corpo",items:["Anatomia del movimento","Ricerca e analisi del movimento","Espressione corporea","Mobilità e flessibilità","Preparazione fisica"]},{mark:"P",title:"Pedagogia e ricerca",items:["Pedagogia della danza","Educazione artistica","Metodo Laban","Progettazione culturale","Tutoraggio accademico"]}]},
 en:{kicker:"03 · Education & expertise",title:<>Knowledge becomes<br/><em>experience.</em></>,intro:"Dance, Peruvian traditions, theatre, circus and pedagogy meet in an interdisciplinary, adaptable and professional practice.",approach:"My approach",methodTitle:<>Every body is unique.<br/>Every movement has meaning.</>,method:"Sessions combine technique, sensitivity and listening with tools developed through performance, education and research. The aim is a safe, motivating space where discipline grows into autonomy and expressive freedom.",skills:[{mark:"D",title:"Dance",items:["Contemporary and classical dance","Traditional Peruvian dance","Composition and group choreography","Improvisation","Aerial dance"]},{mark:"C",title:"Circus & stage",items:["Aerial silks and acrobatics","Contemporary and social circus","Physical theatre and clown","Characters, entertainment and stilts","Interdisciplinary stage creation"]},{mark:"M",title:"Movement & body",items:["Movement anatomy","Movement research and analysis","Physical expression","Mobility and flexibility","Physical conditioning"]},{mark:"P",title:"Education & research",items:["Dance pedagogy","Arts education","Laban Method","Cultural project design","Academic mentoring"]}]}
};
const content={
 it:{...sourceContent.it,kicker:"03 · Competenze in azione",title:<>La pratica prende<br/><em>forma.</em></>,intro:"Competenze concrete per performance, percorsi didattici e progetti che richiedono presenza scenica, cura del corpo e visione creativa.",skills:[{mark:"D",title:"Direzione del movimento",items:["Danza contemporanea e classica","Composizione coreografica","Coreografie di gruppo","Improvvisazione","Narrazione scenica attraverso il corpo"]},{mark:"C",title:"Aerea e circo",items:["Tessuti e acrobatica aerea","Circo contemporaneo","Teatro corporeo","Clown e personaggi","Trampoli e animazione per eventi"]},{mark:"M",title:"Preparazione fisica",items:["Mobilità articolare","Flessibilità funzionale","Allineamento e coordinazione","Forza e preparazione fisica","Consapevolezza corporea"]},{mark:"P",title:"Progettazione didattica",items:["Percorsi individuali e di gruppo","Pratiche per bambini e adulti","Workshop intensivi","Progetti culturali e comunitari","Tutoraggio e accompagnamento creativo"]}]},
 en:{...sourceContent.en,kicker:"03 · Expertise in action",title:<>Practice takes<br/><em>shape.</em></>,intro:"Practical expertise for performances, learning programs and projects that call for stage presence, physical care and creative direction.",skills:[{mark:"D",title:"Movement direction",items:["Contemporary and classical dance","Choreographic composition","Group choreography","Improvisation","Physical storytelling"]},{mark:"C",title:"Aerial & circus",items:["Aerial silks and acrobatics","Contemporary circus","Physical theatre","Clown and character work","Stilts and event entertainment"]},{mark:"M",title:"Physical preparation",items:["Joint mobility","Functional flexibility","Alignment and coordination","Strength and conditioning","Body awareness"]},{mark:"P",title:"Learning design",items:["One-to-one and group programs","Practice for children and adults","Intensive workshops","Cultural and community projects","Creative mentoring"]}]},
 es:{kicker:"03 · Experiencia en acción",title:<>La práctica toma<br/><em>forma.</em></>,intro:"Experiencia concreta para performances, procesos pedagógicos y proyectos que requieren presencia escénica, cuidado corporal y visión creativa.",approach:"Mi enfoque",methodTitle:<>Cada cuerpo es único.<br/>Cada movimiento tiene sentido.</>,method:"Las sesiones unen técnica, sensibilidad y escucha con herramientas nacidas de la escena, la pedagogía y la investigación. El objetivo es crear un espacio seguro y motivador donde la disciplina se convierta en autonomía y libertad expresiva.",skills:[{mark:"D",title:"Dirección del movimiento",items:["Danza contemporánea y clásica","Composición coreográfica","Coreografías grupales","Improvisación","Narración escénica desde el cuerpo"]},{mark:"C",title:"Aéreos y circo",items:["Telas y acrobacia aérea","Circo contemporáneo","Teatro físico","Clown y personajes","Zancos y animación para eventos"]},{mark:"M",title:"Preparación física",items:["Movilidad articular","Flexibilidad funcional","Alineación y coordinación","Fuerza y acondicionamiento físico","Conciencia corporal"]},{mark:"P",title:"Diseño pedagógico",items:["Programas individuales y grupales","Prácticas para niños y adultos","Talleres intensivos","Proyectos culturales y comunitarios","Tutoría y acompañamiento creativo"]}]}
};
export default async function Skills({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){const language=await resolveLanguage(searchParams);const c=content[language];return <Page language={language} kicker={c.kicker} title={c.title} intro={c.intro}><section className="skill-grid">{c.skills.map((s,i)=><article key={s.title}><div className="skill-mark">{s.mark}</div><small>0{i+1}</small><h2>{s.title}</h2><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</section><section className="method-banner"><div className="image-panel image-barre"></div><div><p className="eyebrow">{c.approach}</p><h2>{c.methodTitle}</h2><p>{c.method}</p></div></section></Page>}
