import type { Metadata } from "next";
import Link from "next/link";
import { Page } from "../SiteChrome";
import { localizedHref, resolveLanguage } from "../i18n";
export const metadata: Metadata = { title: "Collaborazioni — Alexandra Huaman", description: "Workshop, lezioni settimanali e percorsi personalizzati." };
const content={
 it:{kicker:"04 · Collaborazioni",title:<>Insieme,<br/><em>il movimento cresce.</em></>,intro:"Proposte per studi, scuole, centri culturali, realtà educative, associazioni e comunità che desiderano lavorare con il corpo attraverso arte e movimento.",options:[["Workshop introduttivi","Esperienze concentrate tra mobilità, danza, improvvisazione e consapevolezza corporea."],["Lezioni continuative","Programmi che costruiscono tecnica, forza, espressività e autonomia nel tempo."],["Progetti artistici e comunitari","Percorsi su misura che integrano danza, circo sociale, educazione e creazione interdisciplinare."]],why:"Perché scegliere Alexandra?",whyTitle:<>Formazione artistica<br/>e pedagogica.</>,reasons:["Esperienza didattica continuativa dal 2015","Laurea in Arti dello Spettacolo con indirizzo Danza","Formazione in circo sociale e lavoro comunitario","Approccio interdisciplinare tra scena, ricerca ed educazione"],cta:"Costruiamo un progetto"},
 en:{kicker:"04 · Collaborations",title:<>Together,<br/><em>movement grows.</em></>,intro:"Programs for studios, schools, cultural centres, educational organisations, associations and communities wishing to work with the body through art and movement.",options:[["Introductory workshops","Focused experiences combining mobility, dance, improvisation and body awareness."],["Ongoing sessions","Programs that build technique, strength, expression and independence over time."],["Artistic and community projects","Tailored work integrating dance, social circus, education and interdisciplinary creation."]],why:"Why work with Alexandra?",whyTitle:<>Artistic and<br/>educational expertise.</>,reasons:["Continuous teaching experience since 2015","Degree in Performing Arts with a specialization in Dance","Training in social circus and community work","An interdisciplinary approach across performance, research and education"],cta:"Let’s create a project"}
};
export default async function Work({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){const language=await resolveLanguage(searchParams);const c=content[language];return <Page language={language} kicker={c.kicker} title={c.title} intro={c.intro}><section className="collab-layout"><div className="collab-photo image-stretch"></div><div className="collab-options">{c.options.map((option,i)=><article key={option[0]}><span>0{i+1}</span><h2>{option[0]}</h2><p>{option[1]}</p></article>)}</div></section><section className="why"><p className="eyebrow dark">{c.why}</p><div><h2>{c.whyTitle}</h2><ul>{c.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><Link className="primary-action dark-button" href={localizedHref("/contatti",language)}>{c.cta} <span>→</span></Link></div></section></Page>}
