import type { Metadata } from "next";
import Link from "next/link";
import { Page } from "../SiteChrome";
import { localizedHref, resolveLanguage } from "../i18n";
export const metadata: Metadata = { title: "Collaborazioni — Alexandra Huaman", description: "Workshop, lezioni settimanali e percorsi personalizzati." };
const content={
 it:{kicker:"04 · Collaborazioni",title:<>Insieme,<br/><em>il movimento cresce.</em></>,intro:"Proposte pensate per palestre, studi Pilates, studi yoga, centri wellness, associazioni e centri per adulti e terza età.",options:[["Workshop introduttivi","Esperienze concentrate per esplorare mobilità, consapevolezza e nuovi strumenti di movimento."],["Lezioni settimanali","Programmi continuativi che costruiscono benessere, forza e autonomia nel tempo."],["Percorsi personalizzati","Proposte su misura per obiettivi, contesti e comunità specifiche."]],why:"Perché scegliere Alexandra?",whyTitle:<>Formazione artistica<br/>e pedagogica.</>,reasons:["Esperienza dal 2015 nell’insegnamento","Approccio attento, adattabile e professionale","Unione di arte, tecnica e benessere"],cta:"Costruiamo un progetto"},
 en:{kicker:"04 · Collaborations",title:<>Together,<br/><em>movement grows.</em></>,intro:"Programs designed for gyms, Pilates and yoga studios, wellness centres, associations, and centres for adults and older people.",options:[["Introductory workshops","Focused experiences exploring mobility, awareness and new tools for movement."],["Weekly sessions","Ongoing programs that build wellbeing, strength and independence over time."],["Tailored programs","Bespoke proposals shaped around specific goals, settings and communities."]],why:"Why work with Alexandra?",whyTitle:<>Artistic and<br/>educational expertise.</>,reasons:["Teaching experience since 2015","An attentive, adaptable and professional approach","A union of art, technique and wellbeing"],cta:"Let’s create a project"}
};
export default async function Work({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){const language=await resolveLanguage(searchParams);const c=content[language];return <Page language={language} kicker={c.kicker} title={c.title} intro={c.intro}><section className="collab-layout"><div className="collab-photo image-stretch"></div><div className="collab-options">{c.options.map((option,i)=><article key={option[0]}><span>0{i+1}</span><h2>{option[0]}</h2><p>{option[1]}</p></article>)}</div></section><section className="why"><p className="eyebrow dark">{c.why}</p><div><h2>{c.whyTitle}</h2><ul>{c.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><Link className="primary-action dark-button" href={localizedHref("/contatti",language)}>{c.cta} <span>→</span></Link></div></section></Page>}
