import type { Metadata } from "next";
import { Page } from "../SiteChrome";
import { localizedHref, resolveLanguage } from "../i18n";
export const metadata: Metadata = { title: "Percorsi — Alexandra Huaman", description: "Stretching & Mobility, Barre e Realing." };
const content={
 it:{kicker:"02 · Percorsi",title:<>Tre strade.<br/><em>Un solo corpo.</em></>,intro:"Ogni percorso dura 50 minuti ed è costruito per incontrare il corpo dove si trova oggi, accompagnandolo con gradualità e precisione.",labels:{program:"Percorso",goal:"Obiettivo",audience:"A chi è rivolto",level:"Livello",structure:"Struttura",cta:"Richiedi informazioni"},paths:[{name:"Stretching & Mobility",sub:"Flessibilità, mobilità e consapevolezza corporea",img:"image-stretch",goal:"Migliorare la mobilità articolare, la flessibilità e la qualità del movimento.",audience:"Sportivi, frequentatori di palestra, danzatori e chi desidera integrare un lavoro di mobilità nella propria routine.",level:"Principiante",structure:"Riscaldamento articolare · Mobilità · Stretching attivo · Rilassamento"},{name:"Barre",sub:"Danza classica, Pilates e preparazione fisica",img:"image-barre",goal:"Sviluppare forza, tonificazione, equilibrio, postura e controllo corporeo.",audience:"Donne dai 25 ai 55 anni che desiderano tonificare il corpo e migliorare postura e coordinazione.",level:"Principiante / Intermedio",structure:"Lavoro alla sbarra e al centro · Gambe e glutei · Core e stabilità · Stretching finale"},{name:"Realing",sub:"Movimento consapevole per il benessere corporeo",img:"image-realing",goal:"Migliorare la mobilità, aumentare la consapevolezza corporea e sviluppare fiducia nel movimento.",audience:"Adulti, persone over 55 e chi ha poca esperienza sportiva o desidera iniziare un percorso dolce e sicuro.",level:"Principiante",structure:"Respirazione · Rilassamento · Mobilità dolce · Consapevolezza corporea · Stretching"}]},
 en:{kicker:"02 · Programs",title:<>Three paths.<br/><em>One body.</em></>,intro:"Each 50-minute program meets the body exactly where it is today, guiding it forward with care, precision and a gradual approach.",labels:{program:"Program",goal:"Purpose",audience:"Who it’s for",level:"Level",structure:"Structure",cta:"Request information"},paths:[{name:"Stretching & Mobility",sub:"Flexibility, mobility and body awareness",img:"image-stretch",goal:"Improve joint mobility, flexibility and the overall quality of movement.",audience:"Athletes, gym-goers, dancers and anyone wishing to integrate mobility work into their routine.",level:"Beginner",structure:"Joint warm-up · Mobility · Active stretching · Relaxation"},{name:"Barre",sub:"Classical dance, Pilates and physical conditioning",img:"image-barre",goal:"Develop strength, tone, balance, posture and body control.",audience:"Women aged 25–55 who want to tone the body and improve posture and coordination.",level:"Beginner / Intermediate",structure:"Barre and centre work · Legs and glutes · Core and stability · Final stretch"},{name:"Realing",sub:"Mindful movement for physical wellbeing",img:"image-realing",goal:"Improve mobility, deepen body awareness and build confidence in movement.",audience:"Adults, people over 55 and anyone with limited sports experience seeking a gentle, safe beginning.",level:"Beginner",structure:"Breathing · Relaxation · Gentle mobility · Body awareness · Stretching"}]}
};
export default async function Paths({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){const language=await resolveLanguage(searchParams);const c=content[language];return <Page language={language} kicker={c.kicker} title={c.title} intro={c.intro}><section className="path-list">{c.paths.map((p,i)=>{const n=String(i+1).padStart(2,"0");return <article className="path-card" key={p.name}><div className={`path-photo ${p.img}`}><span>{n}</span></div><div className="path-copy"><p className="eyebrow dark">{c.labels.program} {n}</p><h2>{p.name}</h2><p className="path-sub">{p.sub}</p><div className="path-facts"><div><small>{c.labels.goal}</small><p>{p.goal}</p></div><div><small>{c.labels.audience}</small><p>{p.audience}</p></div><div><small>{c.labels.level}</small><p>{p.level}</p></div><div><small>{c.labels.structure}</small><p>{p.structure}</p></div></div><a className="inline-arrow" href={localizedHref("/contatti",language)}>{c.labels.cta} <span>→</span></a></div></article>})}</section></Page>}
